[pytest]
addopts = -v -s
testpaths = testcases
python_files = test_*.py

markers =
    role: role-related tests
    account: account-related tests
    student: student-related tests
    teacher: teacher-related tests

filterwarnings =
    # Ignore all DeprecationWarnings from the 'jsonschema' module
    ignore::DeprecationWarning:jsonschema
    # Ignore a specific message regex in a specific category
    ignore:.*U.*mode is deprecated:DeprecationWarning
    # Ignore all warnings
    ignore::